// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpgTACb81OQ_aw4Lx7MKQXo0OeMIM554',
    appId: '1:1073524380669:android:86a9952e65570a45a97f94',
    messagingSenderId: '1073524380669',
    projectId: 'newsapp-e1932',
    databaseURL: 'https://newsapp-e1932-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-e1932.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUjIcs5m1SN_iacPrAwZsxT5wTnE4j_ZM',
    appId: '1:1073524380669:ios:67a4258328951cbca97f94',
    messagingSenderId: '1073524380669',
    projectId: 'newsapp-e1932',
    databaseURL: 'https://newsapp-e1932-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-e1932.appspot.com',
    iosBundleId: 'com.thamaraiselvam.numbers',
  );
}
